### ISSUE TITLE
Poor quality when optimized to 15000 steps

### ISSUE THREAD

**Issue by luocfprime** [ayaanzhaque/instruct-nerf2nerf#101]
Hi, I'm using the latest version of in2n ([2c0d385](https://github.com/ayaanzhaque/instruct-nerf2nerf/commit/2c0d385a724096ef6bae0b8b15afb7b97b9826cf)) and Nerfstudio==1.1.3. I've also encountered similar issues as described in #60.

I used the following command to edit the face scene:

```
ns-train in2n --data datasets/face-processed --load-diroutputs/face-processed/nerfacto/2024-08-05_120014/nerfstudio_models --pipeline.prompt "Turn him into a clown"  --max-num-iterations 15000 nerfstudio-data --downscale-factor 2
```

The camera optimizer config is as follows:

```
       'camera_opt': {
            'optimizer': AdamOptimizerConfig(
                _target=<class 'torch.optim.adam.Adam'>,
                lr=0.0006,
                eps=1e-08,
                max_norm=None,
                weight_decay=0.01
            ),
            'scheduler': ExponentialDecaySchedulerConfig(
                _target=<class 'nerfstudio.engine.schedulers.ExponentialDecayScheduler'>,
                lr_pre_warmup=1e-08,
                lr_final=6e-06,
                warmup_steps=0,
                max_steps=5000,
                ramp='cosine'
            )
        }
```

And I'm pretty sure the images are scaled properly, as I've printed the shape of the input images (torch.Size([1, 3, 364, 493])).

I trained the original scene for 30000 steps, and the rendered results are fine.

This is the edit result I get when using in2n (note how the quality deteriorate after more steps of training):

![image](https://github.com/user-attachments/assets/d1b19299-826a-4dd3-bf7b-0fb72798e8de)
![image](https://github.com/user-attachments/assets/bc878206-e138-4c0b-be76-e7cf6bd7d494)
![image](https://github.com/user-attachments/assets/e208a658-c0f1-40f8-8850-cd5bd85aab01)
![image](https://github.com/user-attachments/assets/81590105-a9e7-40c5-8771-e562a89f02d1)
<img width="1269" alt="image" src="https://github.com/user-attachments/assets/99c8a5e1-ab72-4280-8e16-30e1b313879b">

I wonder if this is normal?

I noticed in #60 where the bear scene is trained for only 2k steps and still obtained good results. Should I decrease the default setting of maximum training steps? Would you be so kind to offer some advice? Thanks!

**Comment by luocfprime** [comment]
Additionally, this is the bear scene (30000 steps for nerf pretraining, 15000 steps for in2n editing):

<img width="1269" alt="image" src="https://github.com/user-attachments/assets/5c632a12-a60f-44b0-855a-fb3a443f0ffe">

But the results looked okay at early steps (~2k steps)

**Comment by ayaanzhaque** [comment]
Sorry for the late response. I think the results sometimes can diverge if trained for too long. We normally trained for just 10k iterations.
