### ISSUE TITLE
denoising strenght

### ISSUE THREAD

**Issue by hugosbnarciso** [ayaanzhaque/instruct-nerf2nerf#13]
Hi,

Is there a way to define the denoising strength ?

Thanks,

**Comment by ayaanzhaque** [comment]
Hi!

You can control the strength of the edit with the guidance parameters. The following command controls the parameters:

`--pipeline.guidance-scale 7.5 --pipeline.image-guidance-scale 1.5`

`guidance-scale` refers to the text guidance scale, so if you would like your edit to change more, increase the guidance scale or decrease the image guidance scale. 

To actually change the denoising strength, we define the range of T from 0.02 to 0.98. We find that this selection of T leads to the best results. If you would like to play with that, the parameters are as follows:

`--pipeline.lower-bound 0.02 --pipeline.upper-bound 0.98`
