### ISSUE TITLE
ns-train -h return no in2n

### ISSUE THREAD

**Issue by cwwjyh** [ayaanzhaque/instruct-nerf2nerf#15]
hello, I have the latest version of nerfstudio. but i find ns-trian -h, no return : in2n, in2n-small, in2n-tiny. 
my version of nerfstudio=0.2.1. how I to fix this problem. 
I am looking forward to your reply. Thank you!
![image](https://user-images.githubusercontent.com/26154160/234015142-5678dec9-4d38-4c05-b548-4a0b3cd7fbdf.png)
![image](https://user-images.githubusercontent.com/26154160/234015192-a1911579-3ede-420f-99db-0e4dd5fc77f2.png)

**Comment by ayaanzhaque** [comment]
How did you install the code? Did you clone the repository? Did you follow all the instructions for installation?

**Comment by cwwjyh** [comment]
Thanks for your reply. First, I clone the Nerfstudio code and install the dependencies. Then I clone instruct nerf2nerf repository. Now, I try to reinstall it.

**Comment by ayaanzhaque** [comment]
Ah ok, here's the steps you should do. You don't have to clone the nerfstudio code, instead you have to clone this repo. 

here are the steps

```bash
conda create --name in2n -y python=3.8
conda activate in2n
python -m pip install --upgrade pip
pip install torch==1.13.1 torchvision functorch --extra-index-url https://download.pytorch.org/whl/cu117
pip install ninja git+https://github.com/NVlabs/tiny-cuda-nn/#subdirectory=bindings/torch
git clone https://github.com/ayaanzhaque/instruct-nerf2nerf.git
cd instruct-nerf2nerf
pip install --upgrade pip setuptools
pip install -e .
ns-train -h
```

Once you do all these, you should have the methods installed. Let me know if you need any more help!

**Comment by cwwjyh** [comment]
> know

Thank you very much. I will try the above steps. If I need more help, I will ask for you.

**Comment by cwwjyh** [comment]
> 

Thank you very much. I have fixed this problem using the above steps

**Comment by ayaanzhaque** [comment]
Great. I'll close this issue.

**Comment by pansanity666** [comment]
> ```shell
> pip install --upgrade pip setuptools
> pip install -e .
> ns-train -h
> ```

Hi, I wonder that is "1.13.1 + CUDA 11.7" mandatory? Does "1.12.1 + CUDA 11.3" work? (it also appears in the nerfstudio documentation). 
Best,
