### ISSUE TITLE
Theoretical Question

### ISSUE THREAD

**Issue by Alaa-Abboud** [ayaanzhaque/instruct-nerf2nerf#16]
Hello 😄 more of a theoretical question: Why do we input a noised latent of the rendered nerf view into the diffusion model instead of any random latent (given that the paper does not rely on SDS loss anymore) in ip2p.py? Am I overlooking a fundamental piece of information?
Appreciate the guidance and help!

**Comment by ayaanzhaque** [comment]
Hello!

We do this primarily to enforce more consistency in each edit. If we input a noised latent of the rendered NeRF, then this latent has structure and information of the current scene, and therefore when it is edited via InstructPix2Pix, it will be a lot more consistent with the rest of the scene than if it was generated via random noise. Therefore, as the NeRF converges towards the edit, InstructPix2Pix produces even more consistent edited images. This is also described in the methods section of the paper Let me know if you have any other questions!

**Comment by Alaa-Abboud** [comment]
Thanks a lot!
