### ISSUE TITLE
NameError: name 'tcnn' is not defined

### ISSUE THREAD

**Issue by amaruzeas** [ayaanzhaque/instruct-nerf2nerf#19]
I was able to train my nfactor just fine, then when I tried to use nerf2nerf  it give me an error

ns-train in2n --data L:\Photogametry_Project\NeRF\amaru --load-dir C:\Users\Cuy\nerfstudio\outputs\amaru\nerfacto\2023-04-25_092552\nerfstudio_models --pipeline.prompt {"prompt"}  --pipeline.guidance-scale 7.5 --pipeline.image-guidance-scale 1.5

NameError: name 'tcnn' is not defined

**Comment by tancik** [comment]
Can you try running `pip install ninja git+https://github.com/NVlabs/tiny-cuda-nn/#subdirectory=bindings/torch`

**Comment by amaruzeas** [comment]
thanks I I will give it a try

**Comment by amaruzeas** [comment]
Thank @tancik it seems that worked, just need to figure it out how to use the pronmt in nerfstudio now :)

**Comment by amaruzeas** [comment]
![image](https://user-images.githubusercontent.com/131799050/234356172-5e0b86da-f80d-4bbf-83db-c9a828258f52.png)

**Comment by amaruzeas** [comment]
so this keep resetting back to 0% then goes all the way to 100% is this normal?

**Comment by ayaanzhaque** [comment]
What do you mean resetting to 0?  If you load the nerfacto model with in2n, it will start the training at 100% (just because the pre-trained model has already been trained for 30k iters). This is expected.

**Comment by amaruzeas** [comment]
![image](https://user-images.githubusercontent.com/131799050/234361040-a3dd5cce-c86f-4ef4-90c6-01125c6644ba.png)

**Comment by amaruzeas** [comment]
see how from 97% goes back to 00%

**Comment by amaruzeas** [comment]
I guess I am still confused how to use in2n and the prompt in nerfstudio

**Comment by ayaanzhaque** [comment]
Oh lol. Its going from 103.97% to 104.00%. The training is going properly. You can set the prompt using the command line, as described in the readme.

`ns-train in2n --data {PROCESSED_DATA_DIR} --load-dir {outputs/.../nerfstudio_models} --pipeline.prompt {"prompt"} --pipeline.guidance-scale 7.5 --pipeline.image-guidance-scale 1.5
`

**Comment by amaruzeas** [comment]
![image](https://user-images.githubusercontent.com/131799050/234366380-45d1b2c1-4091-4c98-8fb1-03542950b143.png)

**Comment by ayaanzhaque** [comment]
The prompt that you added via the command line will show up in that text box. If you want to adjust the prompt during training you can do so. Otherwise, all you have to do is run the command line and then let it train.

**Comment by amaruzeas** [comment]
ah I see thanks, just taking long time to train with in2n (the regular train was much faster) I am using a RTX 4090. so if currently is 107.13% what percentage is completed?

**Comment by ayaanzhaque** [comment]
Ya it takes a lot longer to train than the regular nerfacto because it has to use a diffusion model. It usually will be done around 40k iterations. I would say just check on it in the viewer from time to time to see how the edit is progressing.

**Comment by amaruzeas** [comment]
ah I see thanks a lot. One last question, so everytime I add a different prompt while training will that affect time?

**Comment by ayaanzhaque** [comment]
Ya it will make it take a while to converge to your new edit.
