### ISSUE TITLE
how to reconsturct 3D scene?

### ISSUE THREAD

**Issue by cwwjyh** [ayaanzhaque/instruct-nerf2nerf#20]
![image](https://user-images.githubusercontent.com/26154160/234593403-2389a951-5608-40f7-9a92-bfd04dfdf3dd.png)

Hello, "train a regular nerfacto scene using your data", Is this scene I must use Nerfstudio to reconstruct? Or do your mean I'd better use Nerfstudio for scene reconstruction?

**Comment by ayaanzhaque** [comment]
Basically you must first train a regular nerfacto model using your data, and then you can load that checkpoint into the in2n training so it has something to start editing. You basically need to have the original reconstruction before you can start editing.

**Comment by rozgo** [comment]
An `instant-ngp-bounded` wouldnt work?

**Comment by ayaanzhaque** [comment]
Unfortunately with the current code setup it wouldn't work. This is because the In2n model class inherits the Nerfacto class. However, with some code modifications, it should be possible!

**Comment by starcxl** [comment]
Many thanks for your awesome job! 

May I ask that could you please provide your pre-trained NeRF model parameters on the datasets used in this paper? Just avoid more users training it again to waste computing sources. Pretty thanks!
