### ISSUE TITLE
visualization without nerfstudio viewer 

### ISSUE THREAD

**Issue by pansanity666** [ayaanzhaque/instruct-nerf2nerf#24]
Hi, 
Does the code supports visualization rather than using nerfstudio viewer? (For some reasons, I am not access to the IP of the remote server.)
Best,

**Comment by ayaanzhaque** [comment]
You can swap to using wandb by adding `--vis wandb` to your command. Are you having trouble forwarding the port to view the training?

**Comment by pansanity666** [comment]
To my best knowledge, forwarding the port requires the ip address of the remote server, according to the documentation from nerfstudio. However, in my case, the machine is allocated from the cluster, therefore, it seems that I can't forward the port using ssh -L since the target ip address is unknown.

**Comment by pansanity666** [comment]
> I think doing `-L 7007:localhost:7007` will give you a port at 7007. Then, in your training command, add `--viewer.websocket-port 7007`

If I haven't missed anything, according to  https://docs.nerf.studio/en/latest/quickstart/viewer_quickstart.html, I need to run ```ssh -L 7007:localhost:7007 <username>@<remote-machine-ip>``` in my laptop. However, ```username``` and ```remote-machine-ip``` is unknown.

**Comment by ayaanzhaque** [comment]
Wait, are you training locally or with some remote machine?

**Comment by pansanity666** [comment]
> Wait, are you training locally or with some remote machine?

I am using a remote machine, but for some reason, I actually don't know the ip address. The machine is automatically allocated from a cluster. I can only use it from a specified web page.

**Comment by pansanity666** [comment]
> Wait, are you training locally or with some remote machine?

Maybe I should download the ckpt to my laptop, and launch the viewer in my laptop using ```ns-viewer``` command ?

**Comment by ayaanzhaque** [comment]
@tancik any suggestions here?
