### ISSUE TITLE
504 server Error when loading instructpix2pix from huggingface 

### ISSUE THREAD

**Issue by pansanity666** [ayaanzhaque/instruct-nerf2nerf#25]
Hi, 
I am encountered with the following error when loading pre-trained instructpix2pix from huggingface:
```huggingface_hub.utils._errors.HfHubHTTPError: 504 Server Error: Gateway Time-out for url: https://huggingface.co/api/models/timbrooks/instruct-pix2pix```

Do you have any idea about it ? or is there any workaround like download the ckpt first, and then load the model from local machine?

Thanks.

**Comment by ayaanzhaque** [comment]
I'm not so sure what the issue is here, I'll take a closer look soon.

**Comment by pansanity666** [comment]
> I'm not so sure what the issue is here, I'll take a closer look soon.

It seems to be the server issue from hugginface  according to https://github.com/huggingface/diffusers/issues/3372#issuecomment-1540251863

**Comment by ayaanzhaque** [comment]
Ok great!

**Comment by rockywind** [comment]
I met the same error below.
````
ConnectTimeout: HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: 
/api/models/timbrooks/instruct-pix2pix (Caused by 
ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7ff31d53fc40>, 'Connection to 
192.168.4.75 timed out. (connect timeout=None)'))
````
