### ISSUE TITLE
RuntimeError: CUDA out of memory.

### ISSUE THREAD

**Issue by cuiwenshuai111** [ayaanzhaque/instruct-nerf2nerf#26]
When I try to run 'in2n-tiny' on my 3060 12G,it was happened.Doesn't this method take up 10GB of memory?

**Comment by ayaanzhaque** [comment]
Can you share some details about the memory usage?

**Comment by cuiwenshuai111** [comment]
It is caused by the dataset's size.Your bear dataset is 994 and 783.When i turn it to 497 and 369 like other dataset.It was runned well like other dataset.

**Comment by ayaanzhaque** [comment]
Ah, ya that makes sense. I put a note in the training section that the memory and results work best with images around 512 resolution.
