### ISSUE TITLE
How to debug it through editors such as vscode

### ISSUE THREAD

**Issue by xzr52** [ayaanzhaque/instruct-nerf2nerf#27]
This is a great job. May I ask if this code can be debugged through editors such as vscode and how to proceed? If you could answer, I would greatly appreciate it

**Comment by ayaanzhaque** [comment]
If you install the code from the source, you can make edits to the code in vscode like normal.

**Comment by ayaanzhaque** [comment]
@tancik any suggestions here?

**Comment by xzr52** [comment]
> 这里有什么建议吗？

If it's convenient for you, could you write a startup Python script that allows you to execute the project step by step from this script. Or maybe I don't know about nerf_ Can studio support debugging code like this? If so, I would greatly appreciate it if you could let me know. Thank you again for your answer

**Comment by tancik** [comment]
Does adding a breakpoint directly in the nerfstudio code not work?

**Comment by xzr52** [comment]
Perhaps I am not very familiar with nerfstudio. May I ask which script should I directly set the corresponding command line parameters in nerfstudio, such as ns train nerfacto -- data/nerfstudio/host? For example, is there a definition of a function like parser。thank for you answer!

**Comment by ayaanzhaque** [comment]
Take a look at this issue: https://github.com/ayaanzhaque/instruct-nerf2nerf/issues/22
