### ISSUE TITLE
How to train on data from NeRF-Art

### ISSUE THREAD

**Issue by Dongjiahua** [ayaanzhaque/instruct-nerf2nerf#29]
Hi! Thanks for your great work. I tried to reproduce the results in your paper. However, as a freshman using Nerfstudio, I met some problems with the fungzhou_nature data from NeRF-Art. They are using the LLFF data format and I couldn't find the correct data-parser to use. 
Could you provide the cmd to train on these data?

**Comment by ayaanzhaque** [comment]
Ya so what I did was I just took the images they provided in their dataset and then re-ran ns-process-data myself to get it in the format that nerfstudio uses. Then you can reproduce it in nerfstudio

**Comment by Dongjiahua** [comment]
Thanks! 

Just to confirm. I use 
```
ns-process-data images --data data/fangzhou_nature/images/ --output-dir data/fangzhou_nature_processed
```
to extract it. There comes out a warning:
![image](https://github.com/ayaanzhaque/instruct-nerf2nerf/assets/48640121/abda825b-a3c9-4991-ad19-924aa1034af0)

Is it ok to just have 10 images matched?

**Comment by ayaanzhaque** [comment]
Hmm no, I got a lot more matched images. I've just added my processed data to this folder, so you can just download it. https://drive.google.com/drive/folders/1v4MLNoSwxvSlWb26xvjxeoHpgjhi_s-s
