### ISSUE TITLE
Environment problem

### ISSUE THREAD

**Issue by XinYu-Andy** [ayaanzhaque/instruct-nerf2nerf#3]
May I ask what version of PyTorch you are using? I found that my torch version became 2.0 after following these steps to configure the environment, and as a result, I am unable to successfully import tinycudann.
`pip install torch==1.12.1+cu113 torchvision==0.13.1+cu113 -f https://download.pytorch.org/whl/torch_stable.html
pip install ninja git+https://github.com/NVlabs/tiny-cuda-nn/#subdirectory=bindings/torch
pip install nerfstudio
`
It will report an error if I want to train the second stage (edit part), i.e.:
`ImportError: libtorch_cuda_cu.so: cannot open shared object file: No such file or directory`

**Comment by ayaanzhaque** [comment]
Can you try installing with pytorch 1.13? Use the commands on the tab that says Torch 1.13.1 with CUDA 11.7 here: https://docs.nerf.studio/en/latest/quickstart/installation.html#dependencies

**Comment by ayaanzhaque** [comment]
Ah also, the instructions are a bit confusing. From the installation page, you should only follow the commands up to tinycudann. Then, come back to our readme and go to step 2
