### ISSUE TITLE
bear dataset not updated

### ISSUE THREAD

**Issue by PatrickDDj** [ayaanzhaque/instruct-nerf2nerf#30]
After training in2in on bear dataset, I still get the same scene which is not changed.
training command: ns-train in2n --data data/bear/ --load-dir outputs/bear/nerfacto/2023-05-15_070819/nerfstudio_models  --pipeline.prompt "Turn the bear into a grizzly bear" --pipeline.guidance-scale 7.5 --pipeline.image-guidance-scale 1.5
rendering command: ns-render --load-config outputs/bear/in2n/2023-05-15_085305/config.yml --traj filename --camera-path-filename data/bear/camera_paths/final-path.json --output-path b.mp4

**Comment by ayaanzhaque** [comment]
That's interesting. Can you re-train in2n using a downscaled version of the images? So add this to the end of your train command:

`nerfstudio-data --downscale-factor 2`
