### ISSUE TITLE
Questions about Table 1.

### ISSUE THREAD

**Issue by starcxl** [ayaanzhaque/instruct-nerf2nerf#31]
Hi, Ayaan, many thanks for your work! It's pretty awesome!

May I ask some questions:
(1) Table 1 is performed on which datasets?
(2) Is there a quantitative evaluation code? Just for fair comparisons with other works' results.

**Comment by ayaanzhaque** [comment]
I will provide a folder in the code that contains the evaluation code and some more details on the evaluations performed in our paper!

**Comment by ayaanzhaque** [comment]
https://github.com/ayaanzhaque/instruct-nerf2nerf/tree/main/metrics

Here's the folder with the metric calculations.

In terms of which datasets are used for the calculations in the table, we use 10 total edits between the bear and the face scene. Hopefully this answers your question!
