### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'grad_scaler'

### ISSUE THREAD

**Issue by 870223050** [ayaanzhaque/instruct-nerf2nerf#37]
Describe the bug
When trying to train in2n tiny a grad scaler error keeps popping up.

C:\Users\User\Documents\nerfstudio\nerfstudio\engine\trainer.py:144 in setup

│ 141 │ │ │ │ 'test': loads train/test datasets into memory │
│ 142 │ │ │ │ 'inference': does not load any dataset into memory │
│ 143 │ │ """ │
│ ❱ 144 │ │ self.pipeline = self.config.pipeline.setup( │
│ 145 │ │ │ device=self.device, │
│ 146 │ │ │ test_mode=test_mode, │
│ 147 │ │ │ world_size=self.world_size, │

│ C:\Users\User\Documents\nerfstudio\nerfstudio\configs\base_config.py:57 in setup │

│ 54 │ │
│ 55 │ def setup(self, **kwargs) -> Any: │
│ 56 │ │ """Returns the instantiated object using the config.""" │
│ ❱ 57 │ │ return self._target(self, **kwargs) │
│ 58 │
│ 59 │
│ 60 # Machine related configs │

TypeError: init() got an unexpected keyword argument 'grad_scaler'

**Comment by 870223050** [comment]
nerfstudio 0.3.1

**Comment by 870223050** [comment]
in2n-0.1.0

**Comment by neronicolo** [comment]
Same problem here.

**Comment by ayaanzhaque** [comment]
This only happens with IN2N tiny? I'm not so sure where the error is in your case, can you show the entry point in the IN2N code? The error seems to be on the Nerfstudio side.

**Comment by neronicolo** [comment]
It's the same error as @870223050. I'm not using in2n, not in2n-tiny. And, yes, it looks like it's NS problem. Thanks.

**Comment by ayaanzhaque** [comment]
Hmmm ya I'm not so sure what's going on. Can you make an issue in the nerfstudio repo? If the error throws in Nerfstudio, I can't make any changes in this repo to make it work.

**Comment by neronicolo** [comment]
Sure, thanks.

**Comment by ayaanzhaque** [comment]
Ok I fixed the issue! if you pull the most recent code you should be good to go!
