### ISSUE TITLE
Editing automotive dataset 

### ISSUE THREAD

**Issue by abhigoku10** [ayaanzhaque/instruct-nerf2nerf#38]
@tancik @ayaanzhaque  thansk a lot for sharing the wonderful work just had few queries 
1. has this been tested on the atuomotive dataset like cityscapes and bdd100k 
2. if nto tested , then should we re-train the model on these datasets and would be able to change the color of the car, car-> truck in a given scene 
3. 
![image](https://github.com/ayaanzhaque/instruct-nerf2nerf/assets/22094053/b9135afa-1b74-4b99-adc5-857db87a4d00)

Thansk in advance

**Comment by ayaanzhaque** [comment]
Yes, assuming you can properly reconstruct a NeRF of images from this scene (which is a bit unclear), then you should be able to run it through IN2N and edit things like the color of the car. If you would like to edit individual images, then InstructPix2Pix is the model you should use.
