### ISSUE TITLE
The training speed is a bit slow, how to make it faster

### ISSUE THREAD

**Issue by 870223050** [ayaanzhaque/instruct-nerf2nerf#40]
Thanks for your work, I train very slowly when training the bear dataset, I would like to ask if this is normal? My graphics card is two Quadro RTX 6000, CUDA version is 11.8, and the training command is
`ns-train in2n-tiny --data \bear  --load-dir  \instruct-nerf2nerf\outputs\bear\nerfacto\2023-06-06_111321\nerfstudio_models --pipeline.prompt  "Turn the bear into a grizzly bear" --pipeline.guidance-scale 7.5 --pipeline.image-guidance-scale 1.5  --pipeline.ip2p-device cuda:1  nerfstudio-data   --downscale-factor  8`

44530 (148.43%)     618.377 ms           21 h, 30 m, 15 s     44.08 K
44540 (148.47%)     603.640 ms           21 h, 33 m, 44 s     44.73 K
44550 (148.50%)     623.457 ms           21 h, 28 m, 49 s     43.03 K
44560 (148.53%)     638.317 ms           21 h, 25 m, 7 s      43.84 K
44570 (148.57%)     656.085 ms           21 h, 20 m, 41 s     42.92 K
https://img1.imgtp.com/2023/06/06/mPALwpCR.png
How much time will you need to train, and what percentage of steps will you take after the training is completed?

**Comment by ayaanzhaque** [comment]
Will close this issue as there hasn't been a response in a while.
