### ISSUE TITLE
can the nerf be improved by non-original viewpoint optimization

### ISSUE THREAD

**Issue by metonomas** [ayaanzhaque/instruct-nerf2nerf#42]
clueless general question: are only original training image positions used or can the method restore gaps in training image coverage by iteratively inpainting low information viewpoints? i.e. attempt a 360 iteratively from whatever by referencing the training images similar to control-net but using new view points around a pivot.
I'd like to use footage that wasn't shot with nerfs in mind and optimize it this way. Is this what the model does already?
If not what would it take to modify it for this purpose? This scenario seems more universal and useful as a starting point

**Comment by ayaanzhaque** [comment]
Hi! So currently in our pipeline, we only edit views that are from the original training image coverage. I definitely think it would help to get training views from low info viewpoints, but the only challenge is that it would require hand-crafted camera positions, as most of the scenes we work on are real-world, unbounded scenes, so its non-trivial to sample cameras randomly. If you would like to do this, the best way to do so would be to create a camera path in the viewer, export those camera paths, and then try to load them into the dataloader to use for training. There isn't an easy way to do this and it would require some code adjustments, but definitely doable if you are familiar with Nerfstudio. Good luck!

**Comment by ayaanzhaque** [comment]
If you use the viewer to generate your "pseudo-observations" which you can do by basically setting your framerate to 1 and then picking the cameras you want. Then you can export the json file. Here's how I'd do it:

https://github.com/ayaanzhaque/instruct-nerf2nerf/blob/main/in2n/in2n_pipeline.py#L144
So right here is where I cycle through the list of cameras and load them. 

You can load your camera path by doing this:

`self.cameras_from_path = get_path_from_json(camera_path)`
where `camera_path` is the directory to the camera file. 

Then, just re-write the linked section I gave to this:

```python
# get current camera
current_camera = self.cameras_from_path[current_index].to(self.device)
current_ray_bundle = current_camera.generate_rays(torch.tensor(list(range(1))).unsqueeze(-1))
```

Just make sure you have enough views in your camera path or else you won't get a good edit. Hopefully this helps!

In terms of the new paper, I think using stable diffusion to generate pseudo-views naively would create more artifacts. But its definitely a cool paper!

**Comment by metonomas** [comment]
wow cool, thank you! I'll give it a shot!

**Comment by ayaanzhaque** [comment]
no problem, let me know if you need any help! If you need help using the viewer, check out the nerfstudio docs
