### ISSUE TITLE
About the farm-small dataset

### ISSUE THREAD

**Issue by Cjmsocute** [ayaanzhaque/instruct-nerf2nerf#44]
Hi, thanks for your great work. I'm curious about how you deal with your farm-small dataset. It seems that it's an OPENCV_FISHEYE camera model. I want to use it in the origin NeRF. Actually, I use colmap and https://github.com/NVlabs/instant-ngp/blob/6ee7724370b5e7aa9d514a8c36fae78c112706d9/scripts/colmap2nerf.py to get a transforms.json file from the farm-small images you have provided. But I don't have experience to deal with fisheye dataset in NeRF. It seems that the get_ray function wrote by myself is wrong and I can't get the correct rendering result in NeRF. Or is there other things should be changed compared with the OPENCV camera model? Thanks for your patience.

**Comment by tancik** [comment]
That is correct.
