### ISSUE TITLE
in2n做推理的代码需要自己写吗？还是有现成的py文件

### ISSUE THREAD

**Issue by yoker5262** [ayaanzhaque/instruct-nerf2nerf#45]

**Comment by ayaanzhaque** [comment]
I used Google Translate to understand your question, so I could be wrong, but yes there are code files in the in2n folder of this repository that can be modified and used to train your models. Hopefully this helps!

**Comment by yoker5262** [comment]
I am very sorry that my English level is relatively poor, and I just understand the relevant algorithm of neural radiation field.  Algorithms integrated into the nerfstudio framework are trained and then exported to the yml or ckpt files of the relevant algorithms in the outputs folder.  In your project, I pay more attention to how to use the trained model to do reasoning tasks after the model training is completed.  In your project, I did not see the code related to inference, so I would like to ask you, do I need to write the code myself for the inference code, or is there such inference code in your project?  If I need to write by myself, it is still very difficult for me, I hope you can guide me.

**Comment by ayaanzhaque** [comment]
What type of inference do you mean? Do you want to render out videos of the NeRF? Then you can just use the Nerfstudio viewer, create a camera path, and then export it to video. Here are some instructions for that: https://docs.nerf.studio/en/latest/quickstart/viewer_quickstart.html. When you are training the Instruct-NeRF2NeRF model, it will give you a link to the live viewer which you can use to render out camera paths.

**Comment by yoker5262** [comment]
ok thank u
