### ISSUE TITLE
How can I change instruct-pix2pix to another  image-edited model?

### ISSUE THREAD

**Issue by lxmcwt** [ayaanzhaque/instruct-nerf2nerf#46]
This is a great work. It combines the instruct-pix2pix and NeRF models very well to achieve a very good effect. I noticed another work called HIVE, which is an improved version based on instruct-pix2pix. It adds RLHF on the basis of instruct-pix2pix, and the basic model structure remains unchanged. Now I want to try to replace the instruct-pix2pix component in instruct-nerf2nerf with HIVE to exercise my programming skills. However, since the HIVE model has not been released on Hugging Face like instruct-pix2pix, the method of loading the model needs to be changed. I have tried many methods, but none of them have been successful. This is very frustrating for me. Could you give some feasible suggestions based on your professional knowledge? Thank you very much.

**Comment by ayaanzhaque** [comment]
Will close this issue as there hasn't been a response in a while.
