### ISSUE TITLE
the time generation

### ISSUE THREAD

**Issue by AzimovS** [ayaanzhaque/instruct-nerf2nerf#47]
Hello! 
Thank you for your work!
I wasn't able to find information about the time. Can you please share how long it takes to reach 15k iterations and/or 10k iterations?

**Comment by ayaanzhaque** [comment]
Reaching 15k iterations takes roughly an hour. I believe these details are in the paper, but I apologize if they are not. It also depends a lot on the scene, the number of training images, and their resolution.
