### ISSUE TITLE
some question about CLIP Text-Image Direction Similarity

### ISSUE THREAD

**Issue by cwwjyh** [ayaanzhaque/instruct-nerf2nerf#48]
1. In the below picture, does the paper mean that two scenes are selected, each edited ten times? Or a total of ten edits were made on two scenes? Then the clip text-image Direction similarity is supposed to be calculated case by case, and the sum is averaged.
2. When you calculated the clip text-image direction similarity, did you take the whole training set as input?
 Look forward to your detailed answer. Thank you！
![1686887928422](https://github.com/ayaanzhaque/instruct-nerf2nerf/assets/26154160/2b7d1ac0-c56f-45ab-a86e-d0c0435950c2)

**Comment by ayaanzhaque** [comment]
1. It is 10 total edits split across two scenes. Yes, the clip metrics are calculated per-scene and then averaged when reported.
2. We actually use the rendered images from the camera path used in the renders on the website. We felt it would be fair to perform the metrics on poses that were not in the capture sequence. 

Hopefully these answer your questions!

**Comment by cwwjyh** [comment]
> 2\. to
1. Whether two scenes here were selected at random？
2. Whether the 10 edits are obtained by editing each scene 5 times?

**Comment by ayaanzhaque** [comment]
The two scenes that we used were the face scene and the bear scene. We used all 3 edits of the bear scene and selected 7 edits from the face scene.
