### ISSUE TITLE
problem when run ns-train in2n-tiny

### ISSUE THREAD

**Issue by trltzy** [ayaanzhaque/instruct-nerf2nerf#50]
seemingly I have the problem of downloading huggingface pretrained model, how can I sovle it? thanks
![image](https://github.com/ayaanzhaque/instruct-nerf2nerf/assets/67675349/13f1e79d-d93e-4bc7-825e-683559d2c308)
![image](https://github.com/ayaanzhaque/instruct-nerf2nerf/assets/67675349/51d6eb01-054a-469f-b8b9-51a0cc738b59)

**Comment by ayaanzhaque** [comment]
Did this issue get resolved?

**Comment by w2690831985w** [comment]
> yes, i downloaded the models locally and replace the hugging face links then it's ok

Do I need to download all models from this link https://huggingface.co/timbrooks/instruct-pix2pix/tree/main then repalce root/.cache/huggingface/hub/? And how to replace the huggingface links? Do I need to modify the source code? @trltzy

**Comment by w2690831985w** [comment]
I could access huggingface on a Windows machine, but the remote Linux server can not, so I directly copied the .cache/huggingface/ downloaded on Windows to the linux server, but this did not solve the problem. Do you know what part do I need to modify? @trltzy
