### ISSUE TITLE
I see no modifications in the edited NeRF

### ISSUE THREAD

**Issue by benoriol** [ayaanzhaque/instruct-nerf2nerf#51]
Hello,

I run in2n and see no difference when using ns-viewer after training. In the viewer, I see the prompt "don't change the image" and I'm not sure if it has something to do with it. Also I wanted to point out that I think the command line interface for nerfstudio might have changed and I believe for in2n might have too? Maybe my issue is related to that somehow.

I first run 

```ns-train nerfacto --data data/face --pipeline.datamanager.camera-res-scale-factor 0.5```

Note I used a different CLI arg to downscale compared to the ```--downscale-factor``` suggested in the in2n repo, which I think is now deprecated as argument in nerfstudio.

I then run 

```ns-train in2n --data data/face --load-dir outputs/face/nerfacto/timestamp/nerfstudio_models --prompt "give him a moustache" --pipeline.ip2p-device cuda:1```

Note I didn't use the CLI to specify guidance scales and I used a slightly different argument than the one suggested in the instructions (```--prompt```, which seems to be an alias to ```--pipeline.model.prompt``` as opposed to the suggested ```--pipeline.prompt``` which seemed to not exist.

After it's done training I run ```ns-viewer --load-config outputs/face/in2n/timestamp_2/config.yml``` and connect to the viewer.

In the viewer I can only see the original face nerf with no editing. Moreover, I see a textbox titled "prompt" which shows "don't change the image"

I would appreciate help in trying to figure out what I might be doing wrong and why I am seeing no changes when viewing my trained nerf.

Some potentially relevant output from: ```outputs/face/in2n/timestamp_2/config.yml```:

```diffusion_steps: 20
  edit_count: 1
  edit_rate: 10
  guidance_scale: 7.5
  image_guidance_scale: 1.5
  ip2p_device: cuda:1
  ip2p_use_full_precision: true
  lower_bound: 0.02
```

and then

```
prompt: give him a moustache
```

**Comment by ayaanzhaque** [comment]
I think the issue may be because the prompt isn't being properly parsed in the command line. So `--pipeline.model.prompt` no longer exists? @tancik have some of these arguments been depricated?

**Comment by ayaanzhaque** [comment]
I see, sounds good. So then the downscale resolution is changed now? Could you elaborate a bit more on that

**Comment by ayaanzhaque** [comment]
So pasting it into the code directly solved your problem? that means you somehow aren't parsing the text prompt correctly.

**Comment by Z-YuPeng** [comment]
I also meet the same problem, whether I should specify the "--pipeline.model.prompt"  "--pipeline.prompt" and "--prompt" at the same time when I run n2n? I find the generated training config shows the --pipeline.model.prompt = null when I use the command in the README.md.

**Comment by ayaanzhaque** [comment]
Can you try `--pipeline.prompt`? I believe this is what works

**Comment by Z-YuPeng** [comment]
> Can you try `--pipeline.prompt`? I believe this is what works

yes，i try it. I got very terrible result like [https://github.com/ayaanzhaque/instruct-nerf2nerf/issues/60](url), when i try --pipeline.prompt, i found the value of another two is null as shown in the  gernerated training yamls. I do not know the reason about it.

**Comment by ayaanzhaque** [comment]
then i suspect something in the newer nerfstudio versions is causing this poor quality. I will take a look soon and push some changes

**Comment by ayaanzhaque** [comment]
Let's discuss all this in #60
