### ISSUE TITLE
open3d>=0.16.0 conflict problem

### ISSUE THREAD

**Issue by hjhyunjinkim** [ayaanzhaque/instruct-nerf2nerf#52]
Hi I was wondering if I can use instruct-nerf2nerf with only a open3d dependency of 0.13.0. I am unable to use open3d>=0.16.0 at the moment, and my most recent version is 0.13.0. I am able to download nerfstudio successfully by modifying the `pyproject.toml`, but it seems that I cannot download instruct-nerf2nerf...

```
The conflict is caused by:
    nerfstudio 0.3.2 depends on open3d>=0.16.0
    nerfstudio 0.3.1 depends on open3d>=0.16.0
    nerfstudio 0.3.0 depends on open3d>=0.16.0
```

**Comment by hjhyunjinkim** [comment]
This can be solved by installing nerfstudio first (with open3d=0.13.0) and then installing instruct-nerf2nerf.

**Comment by Violet-Yui** [comment]
@hjhyunjinkim I encountered the same issue. Could you please share in detail how you resolved it?
