### ISSUE TITLE
ns-train in2n: error: argument [{nerfstudio-data,minimal-parser,arkit-data,blender-data,instant-ngp-data,nuscenes-data,dnerf-data,phototourism-data,dycheck-data,scannet-data,sdfstudio-data,nerfosr-data,sitcoms3d-data,colmap}]

### ISSUE THREAD

**Issue by hjhyunjinkim** [ayaanzhaque/instruct-nerf2nerf#53]
Hi I am training in2n on the farm-small data, and I am encountering this error. 

I used `ns-train in2n --data farm-small --load-dir outputs/farm-small/nerfacto/timestamp/nerfstudio_models --pipeline.model.prompt “remove slanted tree from the background”
`

and the error below occurs

`ns-train in2n: error: argument [{nerfstudio-data,minimal-parser,arkit-data,blender-data,instant-ngp-data,nuscenes-data,dnerf-data,phototourism-data,dycheck-data,scannet-data,sdfstudio-data,nerfosr-data,sitcoms3d-data,colmap}]: invalid choice: 'slanted' (choose from 'nerfstudio-data', 'minimal-parser', 'arkit-data', 'blender-data', 'instant-ngp-data', 'nuscenes-data', 'dnerf-data', 'phototourism-data', 'dycheck-data', 'scannet-data', 'sdfstudio-data', 'nerfosr-data', 'sitcoms3d-data', 'colmap')`

Why is slanted a invalid choice, and what do the choices mean?

**Comment by ayaanzhaque** [comment]
I don't see the obvious error here, does it run with a different prompt?

**Comment by hjhyunjinkim** [comment]
My original prompt was "remove the slanted tree from the background", and the same error appeared saying `invalid choice : 'the'`

**Comment by ayaanzhaque** [comment]
What version of nerfstudio do you have?

**Comment by ayaanzhaque** [comment]
Could you try `--pipeline.prompt` instead of ``--pipeline.model.prompt``

**Comment by hjhyunjinkim** [comment]
My nerfstudio version is 0.3.2. Using `--pipeline.prompt` still doesn't work. 

I changed the command to 
`ns-train in2n --data farm-small --load-dir outputs/farm-small/nerfacto/2023-08-06_125549/nerfstudio_models --pipeline.prompt "Make it look like it just snowed" --pipeline.guidance-scale 7.5 --pipeline.image-guidance-scale 1.5
`
The error disappeared and the pipeline components gets loaded, but a new error appears

`Traceback (most recent call last):
  File "/scratch/x2522a05/.conda/envs/nerfstudio/bin/ns-train", line 8, in <module>
    sys.exit(entrypoint())
  File "/scratch/x2522a05/nerfstudio/nerfstudio/scripts/train.py", line 261, in entrypoint
    main(
  File "/scratch/x2522a05/nerfstudio/nerfstudio/scripts/train.py", line 246, in main
    launch(
  File "/scratch/x2522a05/nerfstudio/nerfstudio/scripts/train.py", line 189, in launch
    main_func(local_rank=0, world_size=world_size, config=config)
  File "/scratch/x2522a05/nerfstudio/nerfstudio/scripts/train.py", line 99, in train_loop
    trainer.setup()
  File "/scratch/x2522a05/nerfstudio/nerfstudio/engine/trainer.py", line 185, in setup
    self._load_checkpoint()
  File "/scratch/x2522a05/nerfstudio/nerfstudio/engine/trainer.py", line 410, in _load_checkpoint
    self.optimizers.load_schedulers(loaded_state["schedulers"])
  File "/scratch/x2522a05/nerfstudio/nerfstudio/engine/optimizers.py", line 170, in load_schedulers
    self.schedulers[k].load_state_dict(v)
KeyError: 'proposal_networks'`

I think this is a identical error as #54 . I checked and I have the model checkpoint under the load-dir. Would there be any other suggestions to solve the problem?

**Comment by ayaanzhaque** [comment]
https://github.com/ayaanzhaque/instruct-nerf2nerf/issues/54#issuecomment-1670001226 check out my reply there. I'll go ahead and close this issue.
