### ISSUE TITLE
Using PLY Pointcloud

### ISSUE THREAD

**Issue by matbee-eth** [ayaanzhaque/instruct-nerf2nerf#56]
What would be the workflow for using a PLY for the pointcloud data instead of re-training a NeRF? Or is Instruct simply running against each training image with the diffusion prompt, and THEN training?

**Comment by ayaanzhaque** [comment]
I think re-training the nerf is your best option, atleast with this repo. Theoretically, this our method should work on any multiview reconstruction as long as you can iteratively edit each image in the dataset, but atleast with how its implemented in this codebase, it only works with nerfstudio.
