### ISSUE TITLE
about iteration times

### ISSUE THREAD

**Issue by trltzy** [ayaanzhaque/instruct-nerf2nerf#59]
My nerfacto model was trianed with default iterations 30k, and I set the --max-num-iterations of in2n as 3k, the training seems slow with a very long estimation time. So I have two questions:
1) can I just set a smaller interation time in instruct-nerf2nerf?
2) or I have to set the same interation time as I trained in nerfacto? which means if I want to have a quicker trainning I have to lower the interation of nerfacto first?
![image](https://github.com/ayaanzhaque/instruct-nerf2nerf/assets/67675349/b2a08124-767c-49ee-9ee2-2262a048e72b)
![image](https://github.com/ayaanzhaque/instruct-nerf2nerf/assets/67675349/6f06a488-79aa-4396-bf6b-1a253c019b7d)

**Comment by trltzy** [comment]
thx finally I ran up the project, but it seems the effects of my prompt in webviewer is hard to detect. My prompt is  {"give it a cowboy hat"}, it looks very like my original model. Is there some parameters I should set additionally?

**Comment by ayaanzhaque** [comment]
Are there some edits at all?

`ns-train in2n --data data/nerfstudio/face/ --load-dir {nerfacto model} --pipeline.prompt "give him a cowboy hat" --pipeline.guidance-scale 7.5 --pipeline.image-guidance-scale 1.3 --pipeline.model.near-plane 0.2 nerfstudio-data --scene-scale 2.0 --downscale-factor 2
`
Try with that command. Those are the parameters we used in our paper.

**Comment by ayaanzhaque** [comment]
Let's discuss this in #60
