### ISSUE TITLE
in2n is not registered in the method

### ISSUE THREAD

**Issue by pacifinapacific** [ayaanzhaque/instruct-nerf2nerf#6]
Create nerfstudio by pulling the official docker image and then　installed in2n.
```pip install git+https://github.com/ayaanzhaque/instruct-nerf2nerf ```

The nerfacto training completes successfully, but when I use in2n, I get the following error: 
```ns-train: error argument {nerfacto,depth-nerfacto,instant-ngp,instant-ngp-bounded,mipnerf,semantic-nerfw,vanilla-nerf,tensorf,dnerf,phototourism}:``` 
Can you tell me why in2n is not added t the method?

Launch python3 and import in2n works fine

**Comment by ayaanzhaque** [comment]
It seems to work fine on my end when i create a conda environment, install the dependencies, and then do the pip install. Could you try the instructions exactly as they are listed in the readme?

**Comment by frankjiang** [comment]
You may not install the suitable version of nerfstudio. nerfstudio==0.1.19 (lastest) works fine for me.
Use centos or other system, the nerfstudio may be 0.1.8 or early.
In the early version, the plugins mode is not develop yet.

**Comment by ayaanzhaque** [comment]
It should have the three new methods listed at the bottom, `in2n, in2n-small, in2n-tiny`

**Comment by pacifinapacific** [comment]
Thank you very much.
It was due to the fact that I was using nerfstudio docker version 1.7. Using the latest version (2.0) will work correctly.

**Comment by cwwjyh** [comment]
> It should have the three new methods listed at the bottom, `in2n, in2n-small, in2n-tiny`

hello, I also meet this question. i find ns-trian -h, no return you said  `in2n, in2n-small, in2n-tiny`. my version of nerfstudio=0.2.1. how I to fix this problem.
![1682337704242](https://user-images.githubusercontent.com/26154160/233990385-8089874c-3a56-4124-80a0-17128fabe215.jpg)
![image](https://user-images.githubusercontent.com/26154160/233990475-e0e5dec9-d941-4584-84cc-de62b6e8afd2.png)
