### ISSUE TITLE
Nerfstudio colab? 

### ISSUE THREAD

**Issue by georgeguida** [ayaanzhaque/instruct-nerf2nerf#61]
Hello! Interested in using this in a workshop, is there a working google colab for this? Seems to have some issues with the Nerfstudio colab. Cheers

**Comment by ayaanzhaque** [comment]
Hi, we don't have a working colab for this. From what I understand, the nerfstudio colab may not be working either, so unfortuntaely there are no plans currently to set up a colab for this paper.
