### ISSUE TITLE
How to convert "nerf_llff_data" data to your project?

### ISSUE THREAD

**Issue by starcxl** [ayaanzhaque/instruct-nerf2nerf#63]
Hi, Ayaan, many thanks for your awesome work! It's really interesting!

May I ask how to process the data released by the "NeRF: Neural Radiance Fields" into your project? (The NeRF data link is here: https://drive.google.com/drive/folders/128yBriW1IG_3NJ5Rp7APSTZsJqdJdfc1)

I tried to process "nerf_llff_data/flower" by using the command below:
`ns-process-data images --data Data/flower --output-dir Data/flower --skip_colmap --colmap_model_path sparse/0 --skip_image_processing`

and then using the command below to train the original NeRF:
`ns-train nerfacto --data Data/flower/  --max-num-iterations 90000 nerfstudio-data --downscale-factor 8 `

But the rendering image is very blurry as below, I don't know what causes this problem. Could you please tell me what's happening?
<img width="503" alt="截屏2023-09-21 13 16 26" src="https://github.com/ayaanzhaque/instruct-nerf2nerf/assets/131245463/5c51834d-f58d-4b9f-976c-c7f8ea31b372">

**Comment by ayaanzhaque** [comment]
This is an issue with nerfacto being designed to work well with unbounded scenes and not front-facing scenes. You can find some more information on this [page](https://github.com/nerfstudio-project/nerfstudio/issues/2040).

**Comment by hitachinsk** [comment]
@starcxl Hello, did you solve this problem? I also adopted a front-facing scene to train nerfacto but I got the result just like yours.

**Comment by ayaanzhaque** [comment]
Will close this issue, I recommend asking this in the main nerfstudio repo
