### ISSUE TITLE
How to render images using the same views of the training images? 

### ISSUE THREAD

**Issue by Lxiangyue** [ayaanzhaque/instruct-nerf2nerf#65]
Hi, thanks for your awesome work!

I notice there are three modes of traj: "spiral", "filename", "and interpolate". But none of it could render images the same view as the training images. May I ask how could I render images using the views of the training images?

**Comment by Lxiangyue** [comment]
Ah, I got it.

**Comment by ChchNiu** [comment]
@Lxiangyue I’m facing the same issue with rendering images using the views from the training images. Could you please share how you solved it? Thanks!

**Comment by ChchNiu** [comment]
I solved the issue by using the command ns-render dataset.

Thanks
