### ISSUE TITLE
How to save the modified image dataset?

### ISSUE THREAD

**Issue by w2690831985w** [ayaanzhaque/instruct-nerf2nerf#67]
After running in2n, I got a modified nerf model `./outputs/xxx/in2n/xxx/nerfstudio_models/step-000055000.ckpt`. It did modified the nerf model successfully. However, there is no modified image dataset in this folder, and the in2n command did not modify the original image dataset used to train nerfacto in the `./data` folder. Also, I did not see any modification in the image dataset displyed in the nerfstudio viewer.

So, where can the modified image dataset be displayed? What if I want to save it?

**Comment by ttaa9** [comment]
@ayaanzhaque Is this already implemented somewhere?

**Comment by ayaanzhaque** [comment]
Hi, so the modified dataset is not automatically printed. If you would like to print it, you can access the tensor of images in `in2n_pipeline.py` with the following: `self.datamanager.image_batch["image"]`

Then you can just print the images however you would like.
