### ISSUE TITLE
How to train Nerfacto on LLFF and Blender Datasets?

### ISSUE THREAD

**Issue by hasan1292** [ayaanzhaque/instruct-nerf2nerf#69]
Hi, 

I have a question regarding running your code on LLFF and Blender Datasets.

As Nerfacto is a pre-requisite for running your code, I tried running Nerfacto on LLFF but couldn't get it working. I tried all the available data-loader sub-configs. 

2ndly, I tried to run nerfacto with Blender Dataset, it worked but the generated NeRF model is blurry and distorted. Can you please tell any work around of that?

**Comment by ayaanzhaque** [comment]
Nerfacto doesn't work very well with the LLFF data. You can ask this question in the nerfstudio repo for a better answer.

**Comment by hasan1292** [comment]
Hi, Thank you for quick response. What about Blender dataset? (lego etc?) 

Also, which other datasets did you guys use in your paper In2n?

**Comment by ayaanzhaque** [comment]
I'm not so sure about the blender scenes, I believe they don't work well with nerfacto either. Here's the data we used in our paper: https://drive.google.com/drive/folders/1v4MLNoSwxvSlWb26xvjxeoHpgjhi_s-s?usp=share_link

**Comment by lehduong** [comment]
for training blender with nerfacto, you can try the config in [this](https://github.com/nerfstudio-project/nerfstudio/issues/806#issuecomment-1284327844) comment.
