### ISSUE TITLE
question about custom data processing, transforms.json

### ISSUE THREAD

**Issue by hrz2000** [ayaanzhaque/instruct-nerf2nerf#70]
I noticed that the transform.json format for the given face, bear, and so on is very different from the transfrom.json format obtained by ns-process-data images-data xx. How do you process data? Although they can both train in nerfstudio, in some cases I hope to get the former！

Thank you very much for your work. Could you please take time to answer this question? It won't take too much time.

@ayaanzhaque

**Comment by ayaanzhaque** [comment]
Everything in the folder was processed with nerfstudio, but maybe nerfstudio has updated the ns-process-data command. If you want to re-run it, you can just take all the images in the folder and then run ns-process-data on that folder of images.

**Comment by hrz2000** [comment]
thanks for your early reply! 

By the way, I am suffering from this problem, and I very much hope you can give more opinions，Thank you very much for your efforts
https://github.com/ayaanzhaque/instruct-nerf2nerf/issues/60
