### ISSUE TITLE
tinycudann mismatch

### ISSUE THREAD

**Issue by Iliceth** [ayaanzhaque/instruct-nerf2nerf#73]
I did a fresh install and have a RTX 3060, which would be architecture 86, it insists on using 61. tinycudann is 1.7

```
C:\Users\Andy\Anaconda3\envs\instruct_nerf2nerf\lib\site-packages\tinycudann\modules.py:53: UserWarning: tinycudann was built for lower compute capability (61) than the system's (86). Performance may be suboptimal.
  warnings.warn(f"tinycudann was built for lower compute capability ({cc}) than the system's ({system_compute_capability}). Performance may be suboptimal.")
```

`tiny-cuda-nn warning: FullyFusedMLP is not supported for the selected architecture 61. Falling back to CutlassMLP. For maximum performance, raise the target GPU architecture to 75+.`

Is this normal or can something be altered or updated?

**Comment by Iliceth** [comment]
Update: I found out it is only appears when run on Windows, when run on Ubuntu (via WSL), those warnings don't appear.

**Comment by ayaanzhaque** [comment]
for installation issues, I recommend asking these in the main nerfstudio repo
