### ISSUE TITLE
How can I find and manipulate rendered image durting edting training?

### ISSUE THREAD

**Issue by jhq1234** [ayaanzhaque/instruct-nerf2nerf#76]
Hi, I really enjoy your great work!

But, I have some questions.
To my knowledge, during training, this pipeline uses Instruct Pix2pix to edit images and in2n model train these images.
I want to check these images during training and want to manipulate them.

How can I do this?

Thank you!

**Comment by ayaanzhaque** [comment]
Refer to #67 !
