### ISSUE TITLE
Datasets used in Table 1?

### ISSUE THREAD

**Issue by Lxiangyue** [ayaanzhaque/instruct-nerf2nerf#80]
Hi, Ayaan, many thanks for your work! It's pretty awesome!

May I ask what exactly the [10 scenes](https://github.com/ayaanzhaque/instruct-nerf2nerf/issues/31), text prompt, and S_I and S_T hyperparameters you used to do the qualitative evaluation in Table 1? 

(I have looked through the paper, supplementary, and GitHub issues, and could not find this description. We eagerly want to know the detailed datasets just for fair comparisons :)

**Comment by eyalgomel** [comment]
I have a similar question: are the novel views used for calculating the temporal consistency score the same as those specified in the 'final-path.json' file in the data folder?

Thank you for your great work!

**Comment by ayaanzhaque** [comment]
Sorry for the late response. The path used for the renders is the same as final-path.json yes. For the 10 scenes, we used all the 3 edits from the bear (grizzly, polar, panda), and 7 randomly selected edits from the 9 face edits. Hope this helps!

**Comment by silent-chen** [comment]
Hi, thanks for your brilliant work! May I know what exactly the 7 edits are?
