### ISSUE TITLE
Have a question about CLIP direction consistency score

### ISSUE THREAD

**Issue by soyerin** [ayaanzhaque/instruct-nerf2nerf#82]
Hello, I want to test my model using your metric, named 'CLIP directional consistency score'.
However, I think in your git 'clip_metrics.py', there are only CLIP directional score, not CLIP directional consistency score.

I really await your your quidance on this matter.

Have a nice day!

**Comment by ayaanzhaque** [comment]
You just have to change the inputs to the function when you call it. So if you are doing the directional score, input consecutive frames, and if you are doing similarity score, input the two frames from the separate videos
