### ISSUE TITLE
ns-train in2n-tiny error, 3D model disappears

### ISSUE THREAD

**Issue by wangjinhoon** [ayaanzhaque/instruct-nerf2nerf#84]
The 3D model being trained with the command "ns-train in2n-tiny --data ./lego --load-dir ~/instruct-nerf2nerf/outputs/lego/nerfacto/2023-12-20_174925/nerfstudio_models --pipeline.prompt "change it into a drawing" --pipeline.guidance-scale 7.5 --pipeline.image-guidance-scale 1.5" disappears from the viewer at some point. What did I miss?

before
![Screenshot from 2023-12-21 11-03-05](https://github.com/ayaanzhaque/instruct-nerf2nerf/assets/83506637/2d91111b-ec02-4e09-8964-b552e40b11fe)
after
![Screenshot from 2023-12-21 11-08-27](https://github.com/ayaanzhaque/instruct-nerf2nerf/assets/83506637/c5f817de-556d-4dcb-867f-07c95d18f4bf)

thank for your reply

**Comment by ayaanzhaque** [comment]
Not entirely sure why this would be the case. I suspect that the scene has diverged after training for too many iterations. I've seen this issue before with any nerfstudio model, I recommend creating an issue there. The easiest change would be to train the base nerfacto to 20k iters instead of 30k
