### ISSUE TITLE
AttributeError: 'UNet2DConditionModel' object has no attribute 'attn_processors'

### ISSUE THREAD

**Issue by 870223050** [ayaanzhaque/instruct-nerf2nerf#94]

**Comment by 870223050** [comment]
my code is
`class InstructPix2Pix(nn.Module):
    """InstructPix2Pix implementation
    Args:
        device: device to use
        num_train_timesteps: number of training timesteps
    """

    def __init__(self, device: Union[torch.device, str], num_train_timesteps: int = 1000, ip2p_use_full_precision=False) -> None:
        super().__init__()

        self.device = device
        self.num_train_timesteps = num_train_timesteps
        self.ip2p_use_full_precision = ip2p_use_full_precision

        #pipe = StableDiffusionInstructPix2PixPipeline.from_pretrained(IP2P_SOURCE, torch_dtype=torch.float16, safety_checker=None)
        pipe = StableDiffusionInstructPix2PixPipeline.from_pretrained(IP2P_LOCAL_SOURCE2, torch_dtype=torch.float16, safety_checker=None)
        pipe.scheduler = LCMScheduler.from_config(DDIM_LOCAL_SOURCE_15, subfolder="scheduler")
        #pipe.scheduler = DDIMScheduler.from_pretrained(DDIM_LOCAL_SOURCE_15, subfolder="scheduler")
        pipe.load_lora_weights(LORA_WEIGHT_LOCAL_SOURCE, "pytorch_lora_weights.safetensors")
        print("hugging model load OK!")
        pipe.scheduler.set_timesteps(4)
        assert pipe is not None
        pipe = pipe.to(self.device)
        #pipe = pipe.to("cuda")

        self.pipe = pipe

        # improve memory performance
        pipe.enable_attention_slicing()

        self.scheduler = pipe.scheduler
        self.alphas = self.scheduler.alphas_cumprod.to(self.device)  # type: ignore

        pipe.unet.eval()
        pipe.vae.eval()

        # use for improved quality at cost of higher memory
        if self.ip2p_use_full_precision:
            pipe.unet.float()
            pipe.vae.float()
        else:
            if self.device.index:
                pipe.enable_model_cpu_offload(self.device.index)
            else:
                pipe.enable_model_cpu_offload(0)

        self.unet = pipe.unet
        self.auto_encoder = pipe.vae

        CONSOLE.print("InstructPix2Pix loaded!")`

**Comment by 870223050** [comment]
@ayaanzhaque

**Comment by ayaanzhaque** [comment]
This seems like a diffusers issue. My guess is that you are loading the LoRA model incorrectly. Check the diffusers LoRA APIs to make sure you are loading the model correctly.

**Comment by 870223050** [comment]
thank you very much!
